Fixed Brand Bar Overflow
whitep4nth3r/theclaw.team pull request #13
Opened 2021-12-01 16:45 UTC by tdrayson

Used position:sticky instead of position:fixed to avoid the Logo overflowing outside of Brand Bar when making screensize smaller

2021-12-01 16:58 UTC, whitep4nth3r requested changes

2021-12-01 16:58 UTC, whitep4nth3r commented on styles/Layout.module.css
> +    top:4rem;
Please observe spacing rules! 😁

2021-12-02 13:42 UTC, tdrayson commented on styles/Layout.module.css
> +    top:4rem;
Updated spacing

2021-12-02 13:44 UTC, merged

2021-12-02 13:44 UTC, whitep4nth3r commented
Thanks @tdrayson!